CREATE TABLE `EMPLOYEE` (
  `NAME` varchar(255) NOT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `JOINING_DATE` datetime NOT NULL,
  `SALARY` decimal(10,0) NOT NULL,
  `SSN` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

